defaults: &defaults
  working_directory: ~/workspace
  docker:
      - image: 421990735784.dkr.ecr.us-east-1.amazonaws.com/ci-build-environment:node-8
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY

version: 2
jobs:
  deploy-staging:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: ls -l
      - setup_remote_docker   # We will be building a docker image
      - run:
          command: chmod +x ./deploy/staging.sh
      - run:
          command: ./deploy/staging.sh
      - run:
          command: npm run test

  deploy-prod:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: ls -l
      - setup_remote_docker   # We will be building a docker image
      - run:
          command: chmod +x ./deploy/production.sh
      - run:
          command: ./deploy/production.sh
      - run:
          command: npm run test

workflows:
  version: 2

  build_and_test:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only:
                - develop
      - deploy-prod:
          filters:
            branches:
              only: master
